export const FONT_COLOR_CLASSES = [
  'color-dark-normal',
  'color-default-normal',
  'color-default-hover',
  'color-default-shadow',
  'color-disabled-normal',
  'color-disabled-shadow',
  'color-primary-normal',
  'color-primary-hover',
  'color-primary-shadow',
  'color-success-normal',
  'color-success-hover',
  'color-success-shadow',
  'color-warning-normal',
  'color-warning-hover',
  'color-warning-shadow',
  'color-error-normal',
  'color-error-hover',
  'color-error-shadow',
]

export const BACKGROUND_COLOR_CLASSES = [
  'bg-color-dark-normal',
  'bg-color-default-normal',
  'bg-color-default-hover',
  'bg-color-default-shadow',
  'bg-color-disabled-normal',
  'bg-color-disabled-shadow',
  'bg-color-primary-normal',
  'bg-color-primary-hover',
  'bg-color-primary-shadow',
  'bg-color-success-normal',
  'bg-color-success-hover',
  'bg-color-success-shadow',
  'bg-color-warning-normal',
  'bg-color-warning-hover',
  'bg-color-warning-shadow',
  'bg-color-error-normal',
  'bg-color-error-hover',
  'bg-color-error-shadow',
]

export const PROGRESS_COLOR_CLASSES = [
  'progress-color-dark-normal',
  'progress-color-default-normal',
  'progress-color-default-hover',
  'progress-color-default-shadow',
  'progress-color-disabled-normal',
  'progress-color-disabled-shadow',
  'progress-color-primary-normal',
  'progress-color-primary-hover',
  'progress-color-primary-shadow',
  'progress-color-success-normal',
  'progress-color-success-hover',
  'progress-color-success-shadow',
  'progress-color-warning-normal',
  'progress-color-warning-hover',
  'progress-color-warning-shadow',
  'progress-color-error-normal',
  'progress-color-error-hover',
  'progress-color-error-shadow',
]

